### PR TITLE
fixes #3

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by volrath** [comment]
Thanks for the pull request but you made it over @sxalexander's plugin and not mine (jquery-scrollspy not jquery.scrollspy) and I can't merge it.

**Comment by Guria** [comment]
I'm new at github's pull request's.
This is just oneliner. You could just changet it by yourself.
PS. I've tried yours fork, but it  doesn't seems working for me.

**Comment by volrath** [comment]
Don't worry, I'll change it. I'm sorry my fork it's not working for you, I changed a lot from @sxalexander's version and I didn't take the time to fix the examples. Let me know if I can help you with anything else.

**Comment by Guria** [comment]
Could you describe what you have changed and provide a few working examples?
It hard to compare in commit history since you've changed identations so all strings seems new in diff view.

**Pull request closed without merging**
